### ISSUE TITLE
Accept more than one container in which to look for tabbable nodes

### ISSUE THREAD

**Issue by ZhihaoJia** [davidtheclark/tabbable#10]
It'd be nice to be able to pass more than one element to `tabbable`. The current `tabbable` doesn't allow us to easily find the relative tab orders of elements in multiple containers, if we were to call `tabbable` on each container.

Would it be reasonable to add this feature to `tabbable`? Happy to send a pull request if that's okay.

**Example:**

Suppose the numbers following "el" represent the tab orders of focusable the elements...

container1: el1, el4, el3
container2: el2, el5, el6

Calling `tabbable` on `container1` and `container2` would give us...

container1: el1, el3, el4
container2: el2, el5, el6

However, we wouldn't know how to combine the two lists of `el`s, or know that `el2` from `container2` should be tabbed to before `el3` from `container1`.

**Proposal**

Allow `tabbable` to accept multiple elements: `tabbable(el1, el2, ...)`. `tabbable` returns an array of tabbable nodes in tab order from all of the passed elements/nodes.

**Use cases**

- Composite modals (ie. modals with multiple "dialogs").
- Non-fullscreen modals/overlays (e.g. overlay does not cover a top nav bar).

**Comment by davidtheclark** [comment]
@ZhihaoJia Interesting ... 

Can this be achieved by looking for tabbable nodes in a container that wraps both container1 and container2?

Those sound like some wacky examples, and the idea of bouncing focus across various modals sounds confusing to me. Maybe I'm not envisioning the right UI.

Keep in mind that tabbable is supposed to list the nodes that you would actually focus as you tab through the container. If you tab through your container and come across a node order different from what tabbable returns, there's a bug. But if you want to use tabbable to get some kind of alternate order, different from what tabbing actually does, that's out of scope. Does this apply to your use-cases?

**Comment by davidtheclark** [comment]
Thanks for clarifying @ZhihaoJia! Makes sense.
