### ISSUE TITLE
Option to check a container too

### ISSUE THREAD

**Issue by vonagam** [davidtheclark/tabbable#14]
Right now only nodes within a container get tested, but not a container itself. I have use case when i want a container to be possibly included in resulted array.

In current state i may get what i need, by retrieving tabbables of a parent of a container and then filtering results by inclusion of container. My concern is that of performance. Siblings of a container can be big, while container itself may be small or empty, it may result in much of unnecessary work.

Another way is to add option which will tell to prepend a container to candidates list if it matches one of selectors.

What are your opinion on adding such option? It is ok or is it out of scope of this library?

**Comment by vonagam** [comment]
Just a note for other people, who may need to customize their querying (like in #10):

Found a third, hacky way. Basically right now tabbable takes one argument `el`. And from this supposed element it needs only two things: `ownerDocument ` and `querySelectorAll`. So, you can just pass not an element, but an object with those keys, where `querySelectorAll` implements custom querying.

**Comment by davidtheclark** [comment]
@vonagam: I understand the use case. How about adding an option `includeContainer: boolean`? There aren't any options yet, but we could add a second argument that's an options object. I can't think of any good reason *not* to. I think that would solve your problem, right?

**Comment by vonagam** [comment]
Yes. That would be perfect.

**Comment by davidtheclark** [comment]
👍  open to a PR to introduce this option.

**Comment by davidtheclark** [comment]
Closed by #15.
