### ISSUE TITLE
Not all tabbable elements are in your selector

### ISSUE THREAD

**Issue by adamvleggett** [davidtheclark/tabbable#16]
These come to mind: `area`, `object`.

I see `contenteditable` is impossible to implement correctly.

**Comment by davidtheclark** [comment]
Thanks, @adamvleggett. This is noted in the README as a caveat:

> This plugin ignores the rarely used <area> and <object> elements, which are focusable in some circumstances. (If you need them, maybe PR?)

If you need those and want to create a PR, feel free!

For reference, here's the issue where we discussed the possibility of `contenteditable`: https://github.com/davidtheclark/tabbable/issues/7
