### ISSUE TITLE
couple question

### ISSUE THREAD

**Issue by GrosSacASac** [davidtheclark/tabbable#19]
**First of all, thank you.**

A couple questions; Is it possible to add `<summary>/<details>` ? What about `hidden` html attribute ?

**Comment by davidtheclark** [comment]
@GrosSacASac Happy to add whatever makes the library more accurate! 

Can you please provide some more details? Why `<details`> — that doesn't seem tabbable normally? `<summary>` does, though, at least in Chrome. Let's make sure it's the same cross-browser.

How you tried the `hidden` attribute, and it's not treated correctly? I just tried it in a demo and didn't notice any problem: the `hidden` element was skipped as expected.

**Comment by GrosSacASac** [comment]
Yes `<summary>` does.

<details>
   <summary>test summary</summary>
   <p>Full paragraph below summary</p>
</details>

```
<details>
   <summary>test summary</summary>
   <p>Full paragraph below summary</p>
</details>
```

Yes I tried it works, my bad.

**Comment by GrosSacASac** [comment]
`<audio controls>` and `<video> `

**Comment by davidtheclark** [comment]
Sure, @GrosSacASac: open to a PR adding any fancy new elements that are tabbable!

**Comment by GrosSacASac** [comment]
PR sent !

**Comment by davidtheclark** [comment]
For anybody who comes along this issue and wants to help: the PR #21 was closed but not completed. PRs still welcome if anybody would like to add elements.
