### ISSUE TITLE
Anchors without an href and with a tabindex of 0 don't get picked up

### ISSUE THREAD

**Issue by martinjunior** [davidtheclark/tabbable#2]
This can be fixed by changing line 16 of index.js from..

`|| (candidate.tagName === 'A' && !candidate.href && !candidate.tabIndex)`

to..

`|| (candidate.tagName === 'A' && !candidate.href && (!candidateIndex && candidateIndex !== 0))`

I won't be using tabbable this way, but someone might be.

**Comment by davidtheclark** [comment]
Good find. PR welcome.

**Comment by afraser** [comment]
This is actually common case for single page apps that strive for keyboard accessibility.

**Comment by davidtheclark** [comment]
Closed by https://github.com/davidtheclark/tabbable/pull/3
