### ISSUE TITLE
`summary` element (child of `detail`)

### ISSUE THREAD

**Issue by danielweck** [davidtheclark/tabbable#36]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

`summary` should be added to the list:
https://github.com/davidtheclark/tabbable/blob/c5ad06c85e596fea038c8a59a97324627eaa2784/index.js#L1-L11

**Comment by davidtheclark** [comment]
Thanks, @danielweck. According to https://allyjs.io/data-tables/focusable.html, the `summary` element is not consistently tabbable across supported browsers. In 41f0000d02e52b6a1c835e771bcfcc2f1f98c2f0 I added it to the list of elements in that situation. You could add a `tabindex` to your `summary` elements to ensure they behave consistently, and are recognized by this library.

**Comment by danielweck** [comment]
Very useful response, thank you. However, in our use-case we side-load arbitrary HTML documents, and we avoid as much as possible interfering with the authored markup. We also have the luxury of controlling what browser engine is used, so we can make reliable predictions about the level of support for specific features (like the focusability / tab-ability of `detail`/`summary` elements). So, I will probably just fork your code and continue from there. Thank you! :)

**Comment by davidtheclark** [comment]
Ok, @danielweck 👍  

Another possibility could be to add an option to this library that allows you to add selectors to the list — so in situations like yours you could add more elements.

**Comment by danielweck** [comment]
I recently revisited medialize/a11y.
Still unmaintained.
Also, relies on browser sniffing to address platform-specifc edge cases (not a bad thing per-se, just makes code hard to read + maintain):

https://github.com/medialize/ally.js/blob/master/src/is/tabbable.js

Equivalent of tabbable:

https://github.com/medialize/ally.js/blob/master/src/query/tabsequence.js

**Comment by danielweck** [comment]
I noticed that focusableAreas() in the W3C working draft of 'spatial' navigation (not 'sequential' nav) is "at risk".
https://www.w3.org/TR/css-nav-1/

I wonder if the focus/tab heuristics described in the documentation of medialize/a11y match those that the W3C group have been using to design the specification. Perhaps this bit is in fact underspecified, which is why the feature is marked 'at risk'.
