### ISSUE TITLE
IE 9+ Support 

### ISSUE THREAD

**Issue by knoefel** [davidtheclark/tabbable#4]
Hi David,
just a brief remark: According to your README file you are supporting IE9+. I noticed that since version 1.0.3 you are now using the Array.prototype.find Method in [1]. This will break in IE <= 11.

[1] [index.js#L53](https://github.com/davidtheclark/tabbable/blob/master/index.js#L53)

**Comment by davidtheclark** [comment]
Ugh. Open to PR fixing that.
