### ISSUE TITLE
Elements are excluded if *any* ancestor has `visibility: hidden`, counter to the CSS spec

### ISSUE THREAD

**Issue by craigkovatch** [davidtheclark/tabbable#9]
https://drafts.csswg.org/css-box-3/#visibility-prop

Child elements of a `visibility: hidden` element can themselves be appeared by explicitly setting `visibility: visible`. In this case, any descendants are part of the tab order. tabbable currently excludes these.

**Comment by davidtheclark** [comment]
Thanks! What if the hierarchy is: hidden > visible > unspecified? Are all the children of "visible" also visible? 

Do you have ideas for what specific heuristic would work here?

**Comment by craigkovatch** [comment]
`visible` is an inherited property so the child element will get the value from the closest-ancestor with the property defined.

I just forked the library expecting the change to be a simple 'else if' in `isHidden`, but it's a little more complicated because you still need to walk up the whole tree to see if anything was `display: none`.

**Comment by craigkovatch** [comment]
Example:
`
<body>
<div style="visibility: hidden">
  <div style="visibility: visible">
    <div tabindex="0">lalala</div>
  </div>
</div>
<body>
`

The 'lalala' div should be returned by `tabbable($("body"))`.

`
<body>
<div style="display: none">
  <div style="visibility: visible">
    <div tabindex="0">lalala</div>
  </div>
</div>
<body>
`
In this case, the lalala div should not be returned because it has a parent with `display: none`

**Comment by craigkovatch** [comment]
Looks like jQuery had a similar bug in the past: https://bugs.jqueryui.com/ticket/14596

**Comment by davidtheclark** [comment]
@craigkovatch Makes sense, thanks! I'd welcome a PR making this change. (Not sure how soon I can get to this myself, but will try.)

**Comment by davidtheclark** [comment]
@craigkovatch Had to redo the tests to use a real browser instead of jsdom, because jsdom's `getComputedStyle` doesn't deal properly with inherited styles. But I got it working, and released this fix in 1.0.5.
